
languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Tyler O'Brien"
[params]
  dateFormat = "2 January 2006"
  description = ""
[params.author]
  name = "Tyler O'Brien"
[author]
  headline = "Developer"
  image = "avatar.png"
  bio = "Mostly focused on backend development, trying to keep up with the latest technologies."
  links = [
      { github = "https://github.com/Tyler-OBrien" }
    ]
