colorScheme = "Sapphire"
defaultAppearance = "light"
autoSwitchAppearance = true
showThemeAttribution = false
enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true

showComments = false

fingerprintAlgorithm = "sha256"


[header]
  layout = "basic" # valid options: basic, hamburger, custom

[footer]
  showAppearanceSwitcher = true
  showScrollToTop = true
  showThemeAttribution = false

[homepage]
  layout = "profile" 
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  sharingLinks = [ ]
  showComments = false


[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]




[taxonomy]
  showTermCount = true
