name: cloudflare_bundler_deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        #extended: true
    - name: Build
      run: hugo --minify
    - name: change file permissions
      run: chmod +x bundler/CloudflareWorkerBundler
    - name: Upload
      run: ./CloudflareWorkerBundler bundle
      working-directory: ./bundler
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_BUNDLER }}
        ACCOUNTID: ${{ secrets.ACCOUNTID_BUNDLER }}
        ACCESSKEY: ${{ secrets.ACCESSKEY_BUNDLER }}
        SECRETKEY: ${{ secrets.SECRETKEY_BUNDLER }}
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN_DEPLOY }}
        workingDirectory: "bundler/tyler-obrien-embedded"
    - name: Clean up
      run: ./CloudflareWorkerBundler cleanup
      working-directory: ./bundler
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_BUNDLER }}
        ACCOUNTID: ${{ secrets.ACCOUNTID_BUNDLER }}
        ACCESSKEY: ${{ secrets.ACCESSKEY_BUNDLER }}
        SECRETKEY: ${{ secrets.SECRETKEY_BUNDLER }}