name: couchdb_pages_deploy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
          # extended: true
    - name: Build
      run: hugo --minify
    - name: change file permissions
      run: chmod +x utils/HugoHtmlRewriter
    - name: Rewrite async/defer
      run: utils/HugoHtmlRewriter
      working-directory: ./public
    - name: change file permissions
      run: chmod +x utils/CouchDB-Pages-Uploader
    - name: Upload
      run: utils/CouchDB-Pages-Uploader
      env:
        UPLOAD_DIRECTORY: "public"
        HOSTNAME: "tobrien.dev"
        API_KEY: ${{ secrets.API_KEY }}
        SERVER_URL: "https://tobrien.dev"
        BRANCH_NAME: ${{ github.ref_name }}
