name: couchdb_deploy

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
    - name: Log
      run: echo ${{ github.ref_name }}
    - name: change file permissions
      run: chmod +x utils/CouchDB-Pages-Uploader
    - name: Upload
      run: utils/CouchDB-Pages-Uploader
      env:
        UPLOAD_DIRECTORY: "src"
        HOSTNAME: "tobrien.me"
        API_KEY: ${{ secrets.API_KEY }}
        SERVER_URL: "https://tobrien.me"
        BRANCH_NAME: ${{ github.ref_name }}
